### PR TITLE
editProfile Servlet, by Ziyun

### PR DESCRIPTION
**Pull request by ZiYun1**
Hi I have completed servlet for updating user profile.

Here is test result

### CODE REVIEW

**Comment by leileijng** [comment]
Hi zy, thanks for your hardworking! I feel very well done!

However, something wrong with the email address... Maybe need to check it again?

**Comment by ZiYun1** [comment]
Thanks Lei, yea, I forgot to add the email property.

Here is the newer version test result

**Comment by leileijng** [comment]
Everything looks good! Can merger~

**Comment by Neverfeeel** [comment]
Look good . Continue to merge

**Pull request merged**
